# Generated by Django 6.0.1 on 2026-01-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_delete_savelinkgroup'),
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='save_group',
            field=models.ManyToManyField(related_name='users', to='cards.group_cards'),
        ),
    ]
