# Generated by Django 5.1.7 on 2025-11-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_gallerycard_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/imagecards'),
        ),
    ]
