# Generated by Django 6.0.1 on 2026-01-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_userraiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userraiting',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.group_cards'),
        ),
    ]
