# Generated by Django 6.0.1 on 2026-01-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_savelinkgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveLinkGroup',
        ),
    ]
