# Generated by Django 6.0.1 on 2026-01-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_delete_savelinkgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_cards',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/group-photo'),
        ),
    ]
