# Generated by Django 6.0.1 on 2026-01-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_group_cards_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_cards',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gallerycard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='imagecards'),
        ),
        migrations.AlterField(
            model_name='group_cards',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='group-photo'),
        ),
    ]
